# Generated by Django 5.2.4 on 2025-07-07 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthcare_workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=80)),
                ('patient_preferred_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField()),
                ('consultation_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('healthcare_worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_consultations', to='healthcare_workers.healthcareworker')),
            ],
        ),
    ]
